ALTER TABLE `agc_report_mailing_stats`
  ADD COLUMN `yahoo_recipients` FLOAT UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN `yahoo_delivered` FLOAT UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN `yahoo_opened` FLOAT UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN `yahoo_clicked_total` FLOAT UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN `yahoo_clicked_unique` FLOAT UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN `hotmail_recipients` FLOAT UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN `hotmail_delivered` FLOAT UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN `hotmail_opened` FLOAT UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN `hotmail_clicked_total` FLOAT UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN `hotmail_clicked_unique` FLOAT UNSIGNED NULL DEFAULT NULL
;

